language: go
go:
- 1.13.x
os:
- linux
- osx
- windows
script:
- go build -o dist/kopiatest-$TRAVIS_OS_NAME kopiatest
deploy:
  provider: releases
  api_key:
    secure: kOtIIzB+WCq5bB5Y8TYjS/RqvNwKWtQ8sn4uF/FJ8eeXfWqsuaSukGMztSSEEDW8j4AK1snrzTbS/YrcFe5D3eUT34IsVTUn54T2FpBUBseQRoSbkTK4Qt9lfrRHW1OapfkOjkHpHpu71ukfhFdhYQAeg+WH3TQnF8NpkcS216vztNy3R6jJxvn9Lbo54LXoTh3yWpqi3mhLf4gRVNlano2bNOSEf9YO2bLSrU//+9r1B2q5AqPN+4h58KhOEmiQVLYpeajjOE50p/3pCu/H+zH1hx3a1KG5zGg3hveo3h3BRC2DGTMdn9TGnwTMJkYyRKACzl2tUmNIxKwwIxgjijEAj/pnYnHUoMaDMy2p0NtIGBJu11K7bC/FdrgO9YIgYujKgeCr6xMPvcA797eEfbU1hI3KA1WkFmLHbe7WdShYkJbTgQ4Lb4XtEIuGoj++dYez+2FBRCXTHsAOH8+FS55pgctZE4b2fEPm3OBz+NY2PE/qpzd4jGZMzDUbgrt9qxvzbygsPnn4im4IseCk+Gobb8vsmUTNg0oNIDgnXRStazOLI9p41P9yWnyYGKFPVb3lig9WtOld65QW8SSyV31XZRTFhdAQUAYYZ1FHbqfuRrWdd7pf7IKCMWRqwlKfRD6eylyGHF5xiHEHi7bKte+scGDoYkORYT/32Cu4jIU=
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  draft: true
  on:
    repo: kopia/test
    tags: yes
